btc-ag/service-idl

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/dotnet/DotNetGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/AppConfigGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/AssemblyInfoGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/BasicCSharpSourceGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/CSProjGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ClientConsoleProgramGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DispatcherGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DotNetGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/GeneratorBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ImplementationStubGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/Log4NetConfigGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/NuGetPackageResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProtobufCodecGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProxyDataGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProxyDispatcherGeneratorBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProxyEventGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProxyFactoryGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProxyGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProxyProtocolGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ServerRegistrationGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ServerRunnerGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ServiceAPIGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/TestGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/TypeResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/Util.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/VSSolution.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/9)
> Refactor .NET generator

- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ServiceFaultHandlerFactoryGenerator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/10)
> Added some comments based on review

- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CodecGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CommonProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CppExtensions.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CppGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/IModuleStructureStrategy.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/LegacyProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProjectGeneratorBaseBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProtobufProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProtobufUtil.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ServerRunnerProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/TypeResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/OdbProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/PrinsModuleStructureStrategy.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/12)
> Refactor cpp generator further

- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProtobufCodecGenerator.xtend
Bug fix for issue #18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/22)
> Fixes btc-ag/service-idl#18

- .travis.settings.xml
- .travis.yml
- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/23)
> Add jcenter publishing

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/24)
> Deploy only in upstream fork

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/JavaGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/POMGenerator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/28)
> Depend on protoc

- com.btc.serviceidl.plainjava/pom.xml
- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/26)
> Add plain java module

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/JavaGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/POMGenerator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/27)
> Use new Artifactory URL

- .travis.yml
- com.btc.serviceidl.plainjava/pom.xml
- deploy.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/29)
> Set version to include branch name for plainjava module only

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/JavaGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/POMGenerator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/30)
> Fix protoc path in pom

- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProtobufUtil.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProxyGenerator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/34)
> Fix two more uses of resolve with ProjectType.PROTOBUF

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/JavaGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/POMGenerator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/35)
> Add cab resolver as pluginRepository as well

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/37)
> Added instructions for using the command line generator

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/JavaGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/POMGenerator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/38)
> Let maven build fail on a protoc error

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/40)
> Add link to contribution guidelines to README

- com.btc.serviceidl.plainjava/pom.xml
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/cpp/CppGeneratorTest.xtend
- com.btc.serviceidl/META-INF/MANIFEST.MF
- com.btc.serviceidl/src/com/btc/serviceidl/generator/DefaultGenerationSettingsProvider.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/IGenerationSettingsProvider.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/IdlGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/common/ParameterBundle.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CommonProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CppGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/IProjectSetFactory.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProjectGeneratorBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProjectGeneratorBaseBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProtobufProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ServerRunnerProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeProjectFileGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeProjectSet.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeProjectSetFactory.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeTopLevelProjectFileGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/VSSolution.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/VSSolutionFactory.xtend
Note: this does not yet remove the PRINS-specifics from the generated C++ code, but I would like to merge this to get the integration tests in sync.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/43)
> Generate conan + cmake project files for cpp

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/import-derived.idl
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/import-imported.idl
- com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java
imports to be resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/41)
> Allow multiple input files to be specified on the command line, and

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/IdlGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/dotnet/DotNetGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/AppConfigGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/CSProjGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DispatcherGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DotNetGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/NuGetPackage.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/NuGetPackageResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProxyProtocolGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ServerRunnerGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/TestGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/TypeResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/VSSolution.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/VSSolutionGenerator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/53)
> Provide a state that has successful .NET integration tests

- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProtobufCodecGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProxyDispatcherGeneratorBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/TypeResolver.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/56)
> Fix UUID resolution for dotnet protobuf codec

- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProxyEventGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProxyGenerator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/57)
> Removed erroneous extra argument to Subscribe call in generated .NET code

- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProtobufCodecGenerator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/61)
> Fixed bug in generated C# code (wrong operator)

- FAQ.md
- README.md
Fixes #54 
Fixes #70
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/73)
> Added initial FAQ

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/formatter/IdlFormatterTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/formatting2/IdlFormatter.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/91)
> Fixes btc-ag/service-idl#15

- CODEOWNERS
- README.md
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/cpp/CppGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/dotnet/DotNetGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/JavaGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/protobuf/ProtobufGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/IdlGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CommonProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProjectGeneratorBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProjectGeneratorBaseBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProtobufProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ServerRunnerProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeProjectFileGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeTopLevelProjectFileGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/OdbProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/VSProjectFileGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/VSSolution.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DotNetGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/VSSolutionGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/JavaGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/protobuf/ProtobufGenerator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/89)
> Allow to configure separate output directories and to restrict generated target technologies

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/IdlGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/TestData.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/BasicCppGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/DispatcherGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/HeaderResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProxyGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ServiceAPIGenerator.xtend
Fixes #95
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/98)
> Fix code generation for events targeting C++ ServiceComm 0.11 and 0.12

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/IdlGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/protobuf/ProtobufGenerator.xtend
Fixes #94
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/97)
> Generate Protobuf files only for selected target technologies

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/JavaGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/ProtobufUtilTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/protobuf/ProtobufGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/common/GeneratorUtil.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CodecGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/DispatcherGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProtobufUtil.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProxyGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeTopLevelProjectFileGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DispatcherGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DotNetGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProtobufCodecGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProtobufUtil.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProxyGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/ProxyProtocolGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/Util.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/BasicJavaSourceGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/DispatcherGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ProtobufCodecGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ProtobufUtil.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ProxyGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/protobuf/ProtobufGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/util/Util.xtend
This fixes parts of #90
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/96)
> Fix handling of casing alternatives in IDL file

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/IdlParsingTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/TestExtensions.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/formatter/IdlFormatterTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/IdlGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/TestData.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/good/anonymous-event.idl
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/good/data-struct.idl
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/good/data-typedef.idl
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/good/event.idl
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/good/interface-inheritance.idl
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/good/interface-minimal.idl
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/good/interface-with-enum.idl
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/good/interface-with-sequence-return-type.idl
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/good/interface-with-struct.idl
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/testdata/good/virtual-module.idl
- com.btc.serviceidl/src/com/btc/serviceidl/validation/IdlValidator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/99)
> Create a common test suite and use it for smoke testing the parser, formatter and generator

- README.md
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/JavaGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/DefaultGenerationSettingsProvider.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/IdlGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/BasicJavaSourceGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ClientConsoleGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/DispatcherGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/JavaConstants.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/JavaGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/MavenResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/POMGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ProxyGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ServerRunnerGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ServiceCommVersion.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ServiceFaultHandlerFactoryGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/TestGenerator.xtend
Fixes #51 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/100)
> Allow specifying Java target version, and add (default) support for targeting ServiceComm.Java 0.5

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/JavaGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/JavaGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/MavenResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/POMGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/protobuf/ProtobufGenerator.xtend
Fixes #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/112)
> Use maven artifactId as the directory name in the generated Java code

- com.btc.serviceidl/src/com/btc/serviceidl/IdlRuntimeModule.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/DefaultGenerationSettingsProvider.xtend
Fixes #69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/111)
> Detect misuses of IFileSystemAccess2 during generation

- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProxyGenerator.xtend
Fixes #67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/119)
> Fix further issues with casing alternatives in C++ generator

- com.btc.serviceidl.plainjava/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/123)
> Integrate maven-git-commit-id-plugin

- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CodecGenerator.xtend
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/126)
> Fixed exception handling code generation after changes in Commons 1.9

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/common/ParameterBundleTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/ProtobufUtilTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/common/Extensions.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/common/ParameterBundle.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/DispatcherGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProjectGeneratorBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProjectGeneratorBaseBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProtobufUtil.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/TypeResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/AppConfigGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DotNetGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/TypeResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/Util.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/BasicProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/protobuf/ProtobufGenerator.xtend
Fixes #130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/132)
> Fix duplicate entries in top-level CMakeLists.txt file and clean up ParameterBundle(.Builder)

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/DefaultGenerationSettingsProviderTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DotNetGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/validation/IdlValidator.xtend
Fixes #62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/btc-ag/service-idl/131)
> Add support for building only parts of the supported project types in command line runner

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/cpp/CppGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/IdlGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CppGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/IModuleStructureStrategy.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProjectGeneratorBaseBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cab/CABModuleStructureStrategy.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeTopLevelProjectFileGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/PrinsModuleStructureStrategy.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/VSSolution.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/protobuf/ProtobufGenerator.xtend
> Remove "modules" path prefix when not using PrinsModuleStructureStrategy

- README.md
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/AbstractGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/DefaultGenerationSettingsProviderTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/cpp/CppGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/dotnet/DotNetGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/JavaGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/protobuf/ProtobufGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/DefaultGenerationSettings.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/DefaultGenerationSettingsProvider.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/IGenerationSettings.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/IGenerationSettingsProvider.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/IdlGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CppGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeTopLevelProjectFileGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DotNetGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/BasicProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/JavaGenerator.xtend
> Support reading configuration from properties files

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java
> Fail and output message if no input files were specified.

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/IdlGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/BasicJavaSourceGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ClientConsoleGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ConfigFilesGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/DispatcherGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/InterfaceProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ProxyGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ServerRunnerGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ServiceFaultHandlerFactoryGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/TestGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/Util.xtend
> Fix issue 115

- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DotNetGenerator.xtend
> Fix generation of paket.template file, 'files' section was missing

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/dotnet/UtilTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DotNetGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/Util.xtend
> Remove duplicates from paket.references files

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/cmdline/CommandLineRunnerTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/cpp/CppGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeProjectFileGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeTopLevelProjectFileGenerator.xtend
> Add generation of Windows resource files (C++ generator)

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/dotnet/DotNetGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/CSProjGenerator.xtend
> Define PlatformTarget for .csproj files

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/DefaultGenerationSettingsProviderTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/cpp/CppGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/java/ParentPOMGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/DefaultGenerationSettings.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/DefaultGenerationSettingsProvider.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/IGenerationSettings.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/Maturity.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeTopLevelProjectFileGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DotNetGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/JavaGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/POMGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/java/ParentPOMGenerator.xtend
> Add maturity option to generate either snapshot or release version with corresponding dependencies

- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/DispatcherGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/HeaderResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ImplementationStubGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ServiceAPIGenerator.xtend
> Complete generation of event-related code in C++

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/cpp/CppGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/BasicCppGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CodecGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/HeaderResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProjectGeneratorBaseBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ServerRunnerGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/TestGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeTopLevelProjectFileGenerator.xtend
> Ensure that all generated C++ projects are part of the project set

- com.btc.serviceidl.feature/feature.xml
- com.btc.serviceidl.feature/pom.xml
- com.btc.serviceidl.ide/META-INF/MANIFEST.MF
- com.btc.serviceidl.ide/pom.xml
- com.btc.serviceidl.plainjava/pom.xml
- com.btc.serviceidl.repository/pom.xml
- com.btc.serviceidl.target/pom.xml
- com.btc.serviceidl.tests/META-INF/MANIFEST.MF
- com.btc.serviceidl.tests/pom.xml
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/DefaultGenerationSettingsProviderTest.xtend
- com.btc.serviceidl.ui.tests/META-INF/MANIFEST.MF
- com.btc.serviceidl.ui.tests/pom.xml
- com.btc.serviceidl.ui/META-INF/MANIFEST.MF
- com.btc.serviceidl.ui/pom.xml
- com.btc.serviceidl/META-INF/MANIFEST.MF
- com.btc.serviceidl/pom.xml
- com.btc.serviceidl/src/com/btc/serviceidl/generator/DefaultGenerationSettingsProvider.xtend
- pom.xml
> Use maturity when merging generation settings

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/dotnet/DotNetGeneratorTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/util/tests/UtilTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/AssemblyInfoGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/DotNetGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/util/Util.xtend
> Add generation of version information in AssemblyInfo.cs

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/cpp/CppGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/DefaultGenerationSettingsProvider.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CppGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/HeaderResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/TypeResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cab/CABModuleStructureStrategy.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeTopLevelProjectFileGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/OdbProjectGenerator.xtend
>  Support generation of ExternalDbImpl project using odb with the CMake project system

- com.btc.serviceidl.plainjava/pom.xml
- com.btc.serviceidl.target/com.btc.serviceidl.target.target
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/dotnet/DotNetGeneratorTest.xtend
- com.btc.serviceidl/META-INF/MANIFEST.MF
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/cmake/CMakeTopLevelProjectFileGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/dotnet/AssemblyInfoGenerator.xtend
- pom.xml
Fixes #248 
Also updates Eclipse/Xtext dependencies to fix build
> Fix issue 248

- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/DefaultGenerationSettingsProviderTest.xtend
- com.btc.serviceidl.tests/src/com/btc/serviceidl/tests/generator/cpp/ProxyGeneratorTest.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/DefaultGenerationSettings.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/DefaultGenerationSettingsProvider.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/IGenerationSettings.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/Main.java
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/BasicCppGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/CommonProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/HeaderResolver.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/LegacyProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProjectGeneratorBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProjectGeneratorBaseBase.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProtobufProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ProxyGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/ServerRunnerProjectGenerator.xtend
- com.btc.serviceidl/src/com/btc/serviceidl/generator/cpp/prins/OdbProjectGenerator.xtend
> Allow C++ proxy default timeout override
